### PR TITLE
catch geo buff calculation errors

### PR DESCRIPTION
**Pull request by matthewhanson**
In case of invalid geometries, the error should be caught.

### CODE REVIEW

**Comment by matthewhanson** [comment]
@kamicut we can discuss how best to do this, but we need to catch any general geo errors.

**Comment by kamicut** [comment]
Needs a test, possibly #16

**Comment by kamicut** [comment]
@matthewhanson does this cover https://github.com/AmericanRedCross/osm-stats-workers/issues/13 ?

**Comment by matthewhanson** [comment]
Closing this, it's not the best way to catch errors of this type.

**Pull request closed without merging**
