### PR TITLE
Addressing Issue 231 and improving the robustness of hashtag extraction.

### PR DESCRIPTION
**Pull request by stephan-rayner**
Used better regex, post filter, and de-dup to extract hashtags in a more robust fashion. 

This solves the issue with hashtags that are clumped together without spaces (Issue 231) and it also deals with special characters like `,` and so forth (Issue unknown).

### CODE REVIEW

**Comment by stephan-rayner** [comment]
This solves the issue with hashtags that are clumped together without spaces and it also deals with special characters like `,` and so forth.

**Comment by dalekunce** [comment]
@kamicut can you review and merge?

**Comment by kamicut** [comment]
Sorry for the delay, LGTM. I'll merge and deploy.

**Comment by dalekunce** [comment]
@kamicut did you guys put in a different fix. I remember this being reverted for some node issues?

**Pull request merged**
