### PR TITLE
update poi_count.js

### PR DESCRIPTION
**Pull request by giblet22**
Update poi_count to include additional keys.

### CODE REVIEW

**Comment by dalekunce** [comment]
@matthewhanson would you mind looking at this and merging if it will work.

**Comment by dalekunce** [comment]
@kamicut @matthewhanson bumping this for inclusion with the new work that you are doing.

**Comment by matthewhanson** [comment]
@dalekunce will do. I'll be updating the Travis builds this week to do automated deploy of the master branch to the Lambda function, when I get that working we'll merge this.

**Comment by dalekunce** [comment]
perfect @matthewhanson

**Comment by dalekunce** [comment]
@mojodna this has been sitting for while can we merge this.

**Comment by mojodna** [comment]
This was incorporated into #41

**Pull request closed without merging**
